name: Build

on: [pull_request]

jobs:
  lint:
    name: 🏗️ Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - run: npm ci
    - run: npm run release
